# Generated by Django 2.1 on 2018-08-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitcoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=50, verbose_name='Тотал')),
                ('blocks', models.IntegerField(default=0, verbose_name='Blocks')),
            ],
        ),
    ]
